import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "./components/Footer";
import { SessionProviderWrapper } from "@/components/SessionProviderWrapper"; // we'll create this

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MyShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* SessionProviderWrapper is a client component */}
        <SessionProviderWrapper>
          <Navbar />

          {/* Main content grows to push footer to bottom */}
          <main className="flex-grow">{children}</main>

          <Footer />
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
